# Generated by Django 3.2.7 on 2021-09-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210901_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(blank=True, default='-', max_length=200, verbose_name='CSS класс'),
        ),
    ]
